### ISSUE TITLE
Pour Sud Web : il manque la date

### ISSUE THREAD

**Issue by thom4parisot** [scopyleft/trampolean#1]
Y'a le déroulé complet de la journée mais il manque la date (et le tarif + prise en charge ou non par le DIF).

Endroits où je verrais la date :
- premier fold (au niveau des boutons 'nous contacter')
- déroulé de la journée
- envie d'essayer ?

**Comment by thom4parisot** [comment]
De notre côté : sudweb/2015#25

**Comment by davidbgk** [comment]
La date a été ajoutée + lien vers inscription (et donc tarif)

**Comment by thom4parisot** [comment]
:+1:

**Comment by DirtyF** [comment]
ajouté sur http://sudweb.fr/2015/programme.html
